name: thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
      - papermill
      - nbconvert
      - nbqa
      - ruff
      - pytest
      - optuna
      - tensorboard
      # Optional: experiment tracking
      # - mlflow
